---
output: 
  cleanrmd::html_document_clean:
    theme: style-serif
---

::: {style="text-align: center; font-size: 30px; font-weight: bold; margin-top: 20px; margin-bottom: 20px"}
Population Variation in Chlorophyll Content of ʻAʻaliʻi
:::

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      message = FALSE, 
                      warning = FALSE, 
                      fig.path = "../Output/")
```


```{r}
# Libraries  
library(tidyverse)
library(dplyr)
library(tidytext)
library(here)
library(gganimate)
library(leaflet)
library(cleanrmd)
library(gapminder)
library(hrbrthemes)
library(viridis)
```

```{r}
# Data uploading
functional <- read_csv(here("Final_Project", "Data", "functional.phase.data.csv"))
site <- read_csv(here("Final_Project", "Data", "site.csv"))
```
::: {style="text-align: justify; font-size: 10px; font-weight: bold; margin-top: 20px; margin-bottom: 20px"}
9 populations capturing a 450 mm - 1325 mm MAR precipitation gradient
:::

```{r, fig.width= 10, fig.height= 3, fig.align='center'}
# Map of population source sites

# title on map  
title <- "
<style> 
.maplegend {
position: absolute; 
top: 30px; 
left: 1000%; 
transform: translatex(-10%);
font-weight: bold; 
font-size: 22px; 
text-align: center;
color: #F2F3F2; 
width: 250px;
}
</style> 
<div> 
Population Source Sites of ʻAʻaliʻi 
</div>"

map <- leaflet(data = site) %>% 
  addTiles() %>% 
  addProviderTiles("Esri.WorldImagery") %>% 
  addMarkers(
    lng = -158.2092,
    lat = 21.57249, 
    popup = "Kealia") %>% 
  addMarkers(
    lng = -158.2219,
    lat = 21.51970, 
    popup = "Lower ʻŌhikilolo") %>% 
  addMarkers(
    lng = -158.21953,
    lat = 21.4978, 
    popup = "Keaʻau Hibiscus") %>% 
  addMarkers(
    lng = -158.1939,
    lat = 21.54240, 
    popup = "Kahanahāʻiki") %>% 
  addMarkers(
    lng = -158.0918,
    lat = 21.44530, 
    popup = "ʻĒkahanui") %>% 
  addMarkers(
    lng = -158.0918,
    lat = 21.44530, 
    popup = "Makaha I") %>% 
  addMarkers(
    lng = -157.6810,
    lat = 21.28800, 
    popup = "Koko Head") %>% 
  addMarkers(
    lng = -155.5971,
    lat = 19.77820, 
    popup = "Saddle Road") %>% 
  addControl(html = title, 
             position = "topleft", 
             className = "maplegend")
map

```


```{r, fig.width= 10, fig.height= 3, fig.align='center'}

# Summary stats  
# group control and treatment
# group by phase
# summarise mean

mean_functional <- functional %>% 
  select(Week, Population, Treatment, Chlorophyll) %>% 
  group_by(Week, Population, Treatment) %>% 
  summarize(Chlorophyll = mean(Chlorophyll, na.rm = TRUE))

# save csv file to data folder
write.csv(mean_functional, here("Final_Project", "Data", "mean_functional.csv"))

```
```{r, fig.width= 10, fig.height= 3, fig.align='center'}

# box plot  

# Ungroup the data for plot over time
mean_functional_filled <- mean_functional %>%
    ungroup()

# boxplots!
mean_functional_filled %>%
  ggplot(aes(
    x= Chlorophyll, 
    y= Population, 
    fill = Treatment)) + 
  scale_fill_manual(values = c("C" = "darkgreen", "PD" = "brown")) + 
  geom_boxplot(alpha = 0.5) + 
  geom_jitter(alpha = 0.5) +
    theme(
      legend.position="none",
      plot.title = element_text(size=12, hjust = 0.5, face = "bold"), 
      axis.title.x = element_text(size=10, hjust = 0.5),
      axis.title.y = element_text(size=10, hjust = 0.5),
      axis.text.x = element_text(size = 8), 
      axis.text.y = element_text(size = 8))+
   labs(
     title = "Main Effect of Drought on Chlorophyll Content in ʻAʻaliʻi",
     x = "Chlorophyll Content", 
     y = "Population") + 
  scale_y_discrete(labels = c(
    "Saddle" = "Saddle Road", 
    "Ohikilolo2" = "Lower ʻŌhikilolo B", 
    "Ohikilolo1" = "Lower ʻŌhikilolo A", 
    "Koko" = "Koko Head", 
    "Keaau" = "Keaʻau Hibiscus", 
    "Kahanahaiki" = "Kahanahāʻiki", 
    "Ekahanui" = "ʻĒkahanui")) + 
  facet_wrap(~Treatment)

```

```{r, fig.width= 10, fig.height= 3, fig.align='center'}
# animating a scatter plot
# Chlorophyll content over time
animated_chlplot <- mean_functional_filled  %>% # datasheet
  ggplot(aes(x = Week, # x-axis
             y = Chlorophyll, # y-axis
             color = Treatment,
             group = Treatment)) + # colors
  geom_point(aes(group = seq_along(Week))) +
  geom_line() +
  labs(subtitle = "Population variation in chlorophyll content of ʻaʻaliʻi in response to drought stress over time", # plot subtitle
       caption = "Data sourced from: Greene 2023", # plot caption
       x = "Time (Weeks)", # x-axis label
       y = "Mean Chlorophyll Content") + # y-axis label
  facet_wrap(~Population) + # create panels for each population!
  scale_color_manual(breaks= c("C", "PD"), labels = c("Control Group", "Pulse Drought Group"), values = c("darkgreen", "brown")) + # rename legend variables
  theme(plot.title = element_text(face = "bold", color = "black", hjust = 0.5), # bold title
        axis.text.x = element_text(size = 8), axis.title.x = element_text(size = 10), # adjust x-axis labels
        axis.text.y = element_text(size = 8), axis.title.y = element_text(size = 10),   # adjust y-axis labels
        legend.position = "top", 
        plot.subtitle = element_text(size = 10, hjust = 0.5), 
        legend.title = element_blank())+
  transition_reveal(along = Week)+
  labs(title = "Main Effect of Drought on Chlorphyll Content of ʻAʻaliʻi at Week: {round(frame_along)}") # Display the current Week in the title

# Animate the plot
animate(animated_chlplot, nframes = 50, fps = 10)



```

